### ISSUE TITLE
Is there a year zero?

### ISSUE THREAD

**Issue by tomaka** [lifthrasiir/rust-chrono#103]
When debugging why the year number was off by one in my code, I realized that chrono has a year zero.

In other words, this code prints `0000-01-03T00:00:00` and not `0001-01-03T00:00:00`:

```rust
let base = NaiveDateTime::new(NaiveDate::from_ymd(-1, 1, 1), NaiveTime::from_hms(0, 0, 0));
let result = base + Duration::days(367);
println!("{:?}", result);
```

Since I'm not an expert in calendars, what is the policy about year zero? Is it a bug that there is one, or is it normal? And if it is normal, is there a way to automatically adjust?

**Comment by lifthrasiir** [comment]
It is intentional to have the year zero, which equals to 1 BCE. This is a behavior due to ISO 8601 and makes everything vastly simple and consistent. For the purpose of formatting you can use `Datelike::year_ce` which has no year zero, though.
