### ISSUE TITLE
Convert DateTime<Local> to DateTime<FixedOffset>

### ISSUE THREAD

**Issue by canndrew** [lifthrasiir/rust-chrono#104]
Sorry if this is a silly question but I can't for the life of me figure out a better way to do this. I have a `DateTime<Local>` and I want to convert it to the equivalent `DateTime<FixedOffset>` (in the same timezone). Here is the simplest function I can find to implement this:

```rust
fn local_to_fixed(local_date_time: DateTime<Local>) -> DateTime<FixedOffset> {
    let offset = local_date_time.offset();
    let duration = offset.local_minus_utc();
    let seconds = duration.num_seconds();
    let fixed_offset = FixedOffset::east(seconds as i32);
    let naive_time = local_date_time.naive_local();
    let fixed_date_time = fixed_offset.from_local_datetime(&naive_time).unwrap();
    fixed_date_time
}
```

Is there a better way to do this? Maybe some one-liner that doesn't involve truncating subseconds and unwrapping an operation that can maybe(?) fail?

**Comment by nabijaczleweli** [comment]
Does
```rust
fn local_to_fixed(local_date_time: DateTime<Local>) -> DateTime<FixedOffset> {
    local_date_time.with_timezone(local_date_time.offset())
}
```
work?

**Comment by canndrew** [comment]
Yes it does! I got confused because it looks like `.offset()` returns an `Offset` not a `TimeZone`, and so I missed that. Thank you very much!

**Comment by phiresky** [comment]
this is pretty hard to discover, I think.

My attempt was

```rust
fn now() -> DateTime<FixedOffset> {
    // convert DateTime<Local> to DateTime<FixedOffset>
    let utc_now = chrono::Utc::now();
    let fixed_local_tz = chrono::FixedOffset::from_offset(
        &chrono::Local.offset_from_utc_datetime(&utc_now.naive_utc()),
    );
    utc_now.with_timezone(&fixed_local_tz)
}
```

Maybe your snippet should be added to the part of the doc that says

"FixedOffset: [...] Since it stores the most information and does not depend on the system environment, you would want to normalize other TimeZones into this type."

**Comment by quodlibetor** [comment]
PRs to improve docs are always extremely welcome!
