### ISSUE TITLE
Duration float arithmetics

### ISSUE THREAD

**Issue by DenisKolodin** [lifthrasiir/rust-chrono#106]
`Duration` doesn't implement `Mul<float>`. I find it useful. Why it hasn't implemented?
P.S. I can send a PR if you don't mind.

**Comment by lifthrasiir** [comment]
Chrono does not have `Duration` by itself. You should look at [`libtime`](https://github.com/rust-lang-deprecated/time) (on which Chrono 0.2 depends) and the [standard library](https://doc.rust-lang.org/std/time/struct.Duration.html) (on which Chrono 0.3 is slated to depend).

**Comment by DenisKolodin** [comment]
Sorry, my fault. I hadn't seen it's reexported.
