### ISSUE TITLE
Implement fmt::String for offset::Local?

### ISSUE THREAD

**Issue by daboross** [lifthrasiir/rust-chrono#20]
When trying to use `format()` on `chrono::Local::now()`, I'm getting the following error:
```
error: type `chrono::datetime::DateTime<chrono::offset::Local>` does not implement any method in scope named `format`
```

`Local::now().to_string()` also fails with:
```
error: type `chrono::datetime::DateTime<chrono::offset::Local>` does not implement any method in scope named `to_string`
```

I believe this is due to `chrono::offset::Local` not implementing `std::fmt::String`, where the other offsets do.

**Comment by lifthrasiir** [comment]
Ah, oops. `Local` missing `String` implementation is my fault. I also forgot that `DateTime` with non-`String` `Offset` may still want to format the date and time (and possibly the offset).

**Comment by daboross** [comment]
Thank you!
