### ISSUE TITLE
UTC Offset is not Send (cannot send DateTime across mps::channel)

### ISSUE THREAD

**Issue by SealedSun** [lifthrasiir/rust-chrono#25]
I have a struct with a `DateTime<UTC>` field that I would like to send across a channel, like this:

    pub struct Signal {
      pub time: DateTime<UTC>,
      pub raw: String
    }

But when I want to create the channel, `rustc` complains that

    error: the trait `core::marker::Send` is not implemented for the type `<chrono::offset::utc::UTC as chrono::offset::TimeZone>::Offset` [    E0277]    
    
    let (new_signal_sender, new_signal_rcvr) = channel::<Signal>();
                                               ^~~~~~~~~~~~~~~~~
    note: `<chrono::offset::utc::UTC as chrono::offset::TimeZone>::Offset` cannot be sent between threads safely
    let (new_signal_sender, new_signal_rcvr) = channel::<Signal>();

Now `Send` is easily the part of Rust I understand the least, but I would have expected a DateTime object to be "sendable".

**Comment by lifthrasiir** [comment]
Thank you for reporting. Chrono 0.2.3 fixed this issue.
