### ISSUE TITLE
Consider using an HTML table for strftime format display

### ISSUE THREAD

**Issue by huonw** [lifthrasiir/rust-chrono#31]
Specifically https://lifthrasiir.github.io/rust-chrono/chrono/format/strftime/index.html

rustdoc's markdown supports tables (similar to those that github supports), or one could use inline HTML.

e.g.

| Spec. | Example | Description |
|---|---|---|
| `%Y` | `2001` | The full proleptic Gregorian year, zero-padded to 4 digits. Negative years are allowed in formatting but not in parsing. |
| `%C `| `20` | The proleptic Gregorian year divided by 100, zero-padded to 2 digits. This is floor division, so 100 BCE (year number -99) will print `-1`. |
| `%y` | `01` | The proleptic Gregorian year modulo 100, zero-padded to 2 digits. This is floor division, so 100 BCE (year number -99) will print `99`. |

Source:

```markdown
| Spec. | Example | Description |
|---|---|---|
| `%Y` | `2001` | The full proleptic Gregorian year, zero-padded to 4 digits.  Negative years are allowed in formatting but not in parsing. |
| `%C `| `20` | The proleptic Gregorian year divided by 100, zero-padded to 2 digits. This is floor division, so 100 BCE (year number -99) will print `-1`. |
| `%y` | `01` | The proleptic Gregorian year modulo 100, zero-padded to 2 digits. This is floor division, so 100 BCE (year number -99) will print `99`. |
```

(Unfortunately, I don't know if it is possible to line break the source inside a tables for large cells.)

**Comment by lifthrasiir** [comment]
Good to know. I'll test this.
