### ISSUE TITLE
Generic serialization support (e.g. rustc_serialize)

### ISSUE THREAD

**Issue by SealedSun** [lifthrasiir/rust-chrono#34]
Working with structs that contain `chrono` types and should be sent over a wire or stored in a file is a bit of a pain at the moment, because one has to either
 * implement serialization for the entire struct manually, or
 * create separate 'serialization' structs that store date/time values as dumb integer timestamps and convert between those and the structs that the application actually uses internally

Is there a chance we can have some form of automatic serialization support in chrono? Maybe via `rustc_serialize` and the `RustcEncodable`, `RustcDecodable` traits? Or some other serialization library (`serde` has been mentioned here and there)?

This might raise some tricky questions because, for instance, serialization to JSON would be nicer if date/time values were formatted in an at least somewhat human readable form, whereas pure binary serialization, like with `bincode` would be more efficient with just the timestamp+tz as integers.

**Comment by guersam** [comment]
+1 on `rustc_serialize`

**Comment by lifthrasiir** [comment]
The basic serialization support is now enabled by #36.
