### ISSUE TITLE
Timezone offset colon formatting

### ISSUE THREAD

**Issue by AerialX** [lifthrasiir/rust-chrono#39]
The documentation for both strftime `%z` and the `TimezoneOffset` item indicates that a colon should be printed between the hour and minute values of the timezone offset. This is not the case - which behaviour is intended, is it the code or the documentation that's incorrect?

**Comment by lifthrasiir** [comment]
Good point. The documentation is incorrect this time again; it almost strictly follows the behavior of C `strftime`, where `%z` prints without a colon. I'll fix the documentation soon. Thank you!
