### ISSUE TITLE
Link to "Initial research on the wiki" in README.md is dead

### ISSUE THREAD

**Issue by zetok** [lifthrasiir/rust-chrono#41]
https://github.com/rust-lang/rust/wiki/Lib-datetime redirects to https://github.com/rust-lang/rust

**Comment by lifthrasiir** [comment]
Oh, the wiki is now (somehow) dead. I assume the page is now https://github.com/rust-lang/rust-wiki-backup/blob/master/Lib-datetime.md, thank you for noticing that.
