### ISSUE TITLE
Add period and interval concepts

### ISSUE THREAD

**Issue by manuel-woelker** [lifthrasiir/rust-chrono#44]
This is a proposal to add period and interval concepts like those used in Joda Time
cf.
http://www.joda.org/joda-time/key_period.html
http://www.joda.org/joda-time/key_interval.html

Those are distinct from but interoperable with the existing duration type, and make it possible to describe operations like "add 1 year to this date" (this might be a different number of seconds depending on the date)

Is this something that you would consider for this library?

**Comment by lifthrasiir** [comment]
Not an explicit non-goal for Chrono but I wouldn't pursue that neither. One big reason is that while Chrono closely follows ISO 8601 and other existing practices whenever applicable, there is *no* particular concensus about the non-regular duration arithmetics (ISO 8601 is a representation standard and does not define, say, the result of 2015-08-24 plus 1 month---it only standardizes that "an interval from 2015-08-24 to 2015-08-24 plus 1 month" can be alternatively written as `2015-08-24/P1M`). Implementing that makes Chrono highly opinionated and I don't think that reasonable; that should make into a separate library.

**Comment by pickfire** [comment]
Isn't this in https://en.wikipedia.org/wiki/ISO_8601#Time_intervals?
