### ISSUE TITLE
Parser Error for time like 2015-12-08 04:21:28.000000

### ISSUE THREAD

**Issue by inxi-pc** [lifthrasiir/rust-chrono#53]
```rust
let valid_time_begin_string = rush_hour.valid_time_begin.clone().unwrap();
let valid_time_end_string = rush_hour.valid_time_end.clone().unwrap();
let valid_time_begin = NaiveDateTime::parse_from_str(&valid_time_begin_string, "%Y-%m-%d %H:%M:%S%f").ok();
let valid_time_end = NaiveDateTime::parse_from_str(&valid_time_end_string, "%Y-%m-%d %H:%M:%S").ok();
```
valid_time_begin format is yyyy-MM-dd HH:mm:ss.ffffff, using postgres database type TIMESTAMP WITHOUT TIME ZONE. Sometimes, the .ffffff will be .000000, but another times, it is .123123, it is random.
If i use NaiveDateTime::parse_from_str(&valid_time_begin_string, "%Y-%m-%d %H:%M:%S"), it 
trigger error when time is like 2015-12-08 04:21:28.123456, when i use NaiveDateTime::parse_from_str(&valid_time_begin_string, "%Y-%m-%d %H:%M:%S%f"), it trigger error when time is like 2015-12-08 04:21:28.000000!

**Comment by lifthrasiir** [comment]
Have you tried `%.f`? `%f` only consumes a number, as in `123123` in `.123123`, and won't do what you want in general (it expects a number of nanoseconds).

**Comment by inxi-pc** [comment]
Hi, Thanks for your reply, Sorry for so late to reply.

It is my careless.

Thanks again,
