### ISSUE TITLE
Format Datetime Using Iterator <Item>

### ISSUE THREAD

**Issue by KodrAus** [lifthrasiir/rust-chrono#60]
Is it possible to use an iterator of `Item` to format a `DateTime`, like we can do for parsing to `Parsed`?

If not, I don't think it'd be too hard for me to do myself.

**Comment by lifthrasiir** [comment]
I think you are looking for [`DateTime::format_with_items`](https://lifthrasiir.github.io/rust-chrono/chrono/datetime/struct.DateTime.html#method.format_with_items).

**Comment by KodrAus** [comment]
Genius, thanks. Can't believe I didn't see that...
