### ISSUE TITLE
Local::today() is not today.

### ISSUE THREAD

**Issue by wfraser** [lifthrasiir/rust-chrono#61]
I'm using chrono 0.2.18.

If I run the following test program:

    extern crate chrono;
    use chrono::*;

    fn main() {
        let now = Local::now();
        let today = Local::today();
        println!("{:?}", now);
        println!("{:?}", today);
        println!("{:04}-{:02}-{:02}", now.year(), now.month(), now.day());
        println!("{:04}-{:02}-{:02}", today.year(), today.month(), today.day());
    }

Here's the output I get:

    2016-02-03T16:27:29.757997151-08:00
    2016-02-04-08:00
    2016-02-03
    2016-02-04

`Local::now()` gives me the right results, but `today.day()` looks like it forgot to apply the timezone offset (i.e. it's the same as `UTC::today().day()`).

**Comment by lifthrasiir** [comment]
Thank you for reporting, `Date` was kind of ambiguously defined type at best and lacked some testing. :(

**Comment by wfraser** [comment]
Thanks!
