### ISSUE TITLE
Cannot parse date with DateTime::parse_from_str()

### ISSUE THREAD

**Issue by matthiasbeyer** [lifthrasiir/rust-chrono#68]
Hi,

I'm writing a taskwarrior hook library and I fail parsing the datetime objects I get from taskwarrior:

Output documentation for [taskwarrior](https://taskwarrior.org): https://taskwarrior.org/docs/design/task.html#type_date

The datetime object it exports look like this: "20120110T231200Z", the format is "YYYYMMDDTHHMMSSZ".

My example code:

```rust
    #[test]
    fn test_chrono() {
        let r = DateTime::parse_from_str("20150612T164806Z", "YYYYMMDDTHHMMSSZ");
        println!("{:?}", r);
        println!("{:?}", r.err().unwrap().description());
        assert!(false) // to get the error output
    }
```

It yields:

```
Err(ParseError(Invalid))
"input contains invalid characters"
```

But I do not get any further. What am I doing wrong?

**Comment by lifthrasiir** [comment]
You need to specify the format using `strftime`-like specifiers. [Relevant documentation](https://lifthrasiir.github.io/rust-chrono/chrono/format/strftime/index.html). In this particular case the format string would be `%Y%m%dT%H%M%SZ`.

**Comment by matthiasbeyer** [comment]
Embarrassing. I'm sorry! :sob:

**Comment by peterjoel** [comment]
Using the suggested format, I still get an error for this:

```rust
use chrono::*;
fn main() {
    let r = DateTime::parse_from_str("20191022T193220Z", "%Y%m%dT%H%M%SZ");
    println!("{:?}", r);
}
```

```
Err(ParseError(NotEnough))
```

Using any of the timezone indicators from the docs, e.g. `%z` or `%:z`, work ok. But it cannot parse a date string that ends with a `Z`.
