### ISSUE TITLE
Confusing (documentation of) formatting of fractional seconds

### ISSUE THREAD

**Issue by troplin** [lifthrasiir/rust-chrono#71]
I'm quite confused about the formatting of fractional seconds. The documentation seems to be inconsistent and there are some places in the code that I think are bugs (just from looking at the code, not actually encountered them).

I'm using `log4rs` for logging in my application and there was this strange effect with fractional seconds:
Im using the `{d}` formatter in, which according to the documentation uses the ISO 6801 format.

Now, almost all entries have a precision of exactly 9 digits, but every now and then (maybe after about 50 entries), there is an entry with 6 digits.

Example:
```text
2016-04-19T21:44:43.983416760+00:00 ...
2016-04-19T21:44:49.199616120+00:00 ...
2016-04-19T21:45:30.639604840+00:00 ...
2016-04-19T21:45:30.641324440+00:00 ...
2016-04-19T21:45:43.573686080+00:00 ...
2016-04-19T23:47:39.533879920+00:00 ...
2016-04-20T01:48:21.214988880+00:00 ...
2016-04-20T03:49:14.854611400+00:00 ...
2016-04-20T05:50:07.723535600+00:00 ...
2016-04-20T07:50:59.404401+00:00 ...
2016-04-20T08:55:44.798731960+00:00 ...
2016-04-20T08:55:44.799131760+00:00 ...
2016-04-20T08:57:44.209481360+00:00 ...
2016-04-20T08:57:44.266084640+00:00 ...
2016-04-20T08:57:44.293876080+00:00 ...
2016-04-20T09:51:53.068258480+00:00 ...
2016-04-20T11:52:43.275364520+00:00 ...
2016-04-20T13:53:36.395558920+00:00 ...
2016-04-20T15:54:27.967924880+00:00 ...
2016-04-20T17:55:19.631437880+00:00 ...
2016-04-20T18:17:03.745529880+00:00 ...
2016-04-20T18:30:06.031285560+00:00 ...
```

First I was confused about this, thought that it was a bug, then I read the documentation and see that it's probably by design.
But I really don't see the advantage of this. It cannot be used as fixed width, but it's also not really variable width. It combines the disadvantages of both IMO.

Then, digging through the code, I found this comment in `format/mod.rs:423`
```rust
                    RFC3339 => // (almost) same to `%Y-%m-%dT%H:%M:%S.%f%z`
```
buf documentation says:
```text
6. `%+`:
   This one is close to, but not identical to, `%Y-%m-%dT%H:%M:%S%.f%z`.
```
and according to the documentation, the `%f` specifier is fixed precision of 9, only `%.f` uses steps of 3/6/9.
Now, which one is correct?

There's also an typo in the documentation (`strftime.rs:134`):
```text
   The variant `%.3f`, `%.3f` and `%.3f` are left-aligned and print 3, 6 or 9 fractional digits
```

And I'm really not sure if the `nano == 0` cases here are copy/paste bugs:
```rust
                    Nanosecond3 =>
                        time.map(|t| {
                            let nano = t.nanosecond() % 1_000_000_000;
                            if nano == 0 {
                                write!(w, ".000")
                            } else {
                                write!(w, ".{:03}", nano / 1_000_000)
                            }
                        }),
                    Nanosecond6 =>
                        time.map(|t| {
                            let nano = t.nanosecond() % 1_000_000_000;
                            if nano == 0 {
                                write!(w, ".000")
                            } else {
                                write!(w, ".{:06}", nano / 1_000)
                            }
                        }),
                    Nanosecond9 =>
                        time.map(|t| {
                            let nano = t.nanosecond() % 1_000_000_000;
                            if nano == 0 {
                                write!(w, ".000")
                            } else {
                                write!(w, ".{:09}", nano)
                            }
                        }),
```
I don't even understand, why this case is handled separately, so I'm possibly misunderstanding something...

**Comment by lifthrasiir** [comment]
Thank you for the report. The `nano == 0` cases are, uh, indeed errors (me being a bad reviewer)! The typos for `%.[369]f` documentations are also my faults. I'll issue a bugfix release shortly.

> First I was confused about this, thought that it was a bug, then I read the documentation and see that it's probably by design.
> But I really don't see the advantage of this. It cannot be used as fixed width, but it's also not really variable width. It combines the disadvantages of both IMO.

`%+` is a locale-dependent representation for the date and time in the typical `strftime` implementations. In the other words, you probably should not rely on the exact format of `%+` anyway. I'm not really sure why log4rs went with `%+`, but I'll put a note to that documentation for the curious.

It should also be noted that the fractional seconds, `%f`, are not really universal either; `strftime` works on `struct tm` which has only second granularity, and Chrono's usage of `%f` comes from other languages imitating `strftime` (e.g. Python). `%f` being 0, 3, 6 or 9 digits is thus a direct reflection of Chrono's constructor functions and nothing else.
