### ISSUE TITLE
Implement `Default` for `DateTime<FixedOffset>`

### ISSUE THREAD

**Issue by indiv0** [lifthrasiir/rust-chrono#73]
Would it be viable to implement the `Default` trait for `DateTime<FixedOffset>`?

Adding this in would be very useful for deserializing AWS responses in the [rusoto](https://github.com/rusoto/rusoto) project.

**Comment by lifthrasiir** [comment]
I don't think it is viable; `DateTime` has no special value (something like NaN in floats). I'm not sure why it would be useful for rusoto, can I ask you for the details?

**Comment by indiv0** [comment]
Rusoto has a codegen crate which is used to generate the structs necessary to deserialize responses from AWS. Those types have `#[derive(Default)]`, which isn't valid all of the fields also derive `Default`. Some of those structs have fields which correspond to timestamp responses from AWS, which we'd like to deserialize to `DateTime<FixedOffset>` instead of `String` (which is what we do now). However, we can't do this as changing the type from `String` to `DateTime<FixedOffset>` results in the structs being unable to implement `Default`.

**Comment by lifthrasiir** [comment]
@indiv0 That exactly sounds like that you actually need `Option<DateTime<FixedOffset>>`. AFAIK It does not affect the (de)serialization format (unless the value itself *may* be serialized into `null`, but `DateTime` doesn't).

**Comment by indiv0** [comment]
@lifthrasiir I've pulled you into the discussion in the PR: https://github.com/rusoto/rusoto/pull/235. Per what I wrote at the end there (depending on what the rusoto maintainers say), I don't think `Option<DateTime<FixedOffset>>` will be viable, since there are cases where we expect a `DateTime<FixedOffset>` everytime, so it can't be optional in those cases.

Keeping that in mind, wouldn't it be possible to just default to the equivalent of `0000-01-01T00:00:00-00:00`?

**Comment by indiv0** [comment]
Per the comments made [here](https://github.com/rusoto/rusoto/pull/235#issuecomment-221175324), and the relevant issue that was opened [here](https://github.com/rusoto/rusoto/issues/272), rusoto has decided to instead move away from providing `Default` implementations for the auto-generated types. As such, I'm going to close this issue.

Thank you for your help and input!
