### ISSUE TITLE
Timestamp in milliseconds/nanoseconds

### ISSUE THREAD

**Issue by craftytrickster** [lifthrasiir/rust-chrono#74]
I would like to have the ability to get the amount of milliseconds (or maybe even nanoseconds) since unix epoch. 

Currently, this seems to only be available in seconds:
https://lifthrasiir.github.io/rust-chrono/chrono/datetime/struct.DateTime.html#method.timestamp

Is there a reason not to provide two extra methods like?
`timestamp_milliseconds`
`timestamp_nanoseconds`

If it is indeed desired, I can open a PR to add them.

Please let me know.

**Comment by craftytrickster** [comment]
I would have closed this much earlier, but for some reason I was never received an email notification about the above PR.

Thanks for the work.

**Comment by lifthrasiir** [comment]
Ah indeed, I guess it wasn't closed automatically since it lacked comments in the form of "Fixes #ISSUENO" or similar.
