### ISSUE TITLE
Documentation - List / link to shortcodes table in documentation

### ISSUE THREAD

**Issue by sekjun9878** [lifthrasiir/rust-chrono#82]
Hello,

On the documentation page about parsing, an example is given regarding using custom formats for parsing but there is no list of shortcodes that can be used as the format string, nor any link to any standard leaving readers feeling confused as to what format codes are implemented.

https://lifthrasiir.github.io/rust-chrono/chrono/

It would be better for accessibility if the format codes were clearly listed.

**Comment by sekjun9878** [comment]
Which can be found here http://blog.jwilm.io/retry-after/chrono/format/strftime/index.html

**Comment by lifthrasiir** [comment]
@sekjun9878 Hopefully this should be better. (I also synchronized some main documentation previously only available in `README.md`.)

**Comment by sekjun9878** [comment]
Looks good. Thanks, that was fast! :)
