### ISSUE TITLE
What is YMDF? Where is DateImpl defined?

### ISSUE THREAD

**Issue by iamsebastian** [lifthrasiir/rust-chrono#83]
After some search in the world wide web, I'm not sure, if I now really know, what it is.

If I serialize a `NaiveDate` or `NaiveDateTime` *(2016-07-27 06:07:08)* to JSON, I get a date object, which looks like this:

NaiveDateTime:
```json
{
   "time" : {
      "frac" : 0,
      "secs" : 22028
   },
   "date" : {
      "ymdf" : 16518419
   }
}
```

NaiveDate:
```json
"date" : {
   "ymdf" : 16518419
}
```

The implementation is here:
https://github.com/lifthrasiir/rust-chrono/blob/f41de9b41f61936763840ffaefbec4e30e876c75/src/naive/date.rs#L54

## The question
How can I translate these integers **to a unix timestamp**, so that I can create a `new Date()` in my Ember.js Frontend? It is not clear, how to transform this.
I use a Postgres-Rust-API, where I deserialize the postgres timestamps to NaiveDateTime. These NaiveDateTimes should also get deserialized and send out via JSON to the Ember.js Frontend. But I don't know, how to interprete this `ymdf`.

## Also `DateImpl` could not be found
If I search for `DateImpl` in the whole repository via GitHub, I can not find any match, but the 

```rust
use self::internals::DateImpl;
```
line. What is `self::internals`?

**Comment by lifthrasiir** [comment]
`ymdf` is an internal representation of `NaiveDate` as you've linked; more specifically, lower 4 bits are "flags" for quickly calculating weekdays, next 9 bits are the day of year (1 through 366), remaining bits are the Gregorian year number (year 0 being 1 BCE). So if you want to manually interpret that, in principle you can do the following (assuming you want to get the midnight UTC of that date):

    year = (ymdf >> 13) - 1
    doy = ((ymdf >> 4) & 511) - 1
    timestamp = 86400 * ((year * 365 + year div 4 - year div 100 + year div 400) -
                         (1969 * 365 + 1969 div 4 - 1969 div 100 + 1969 div 400) + doy)

I have regarded the default serialization implementations as the most efficient and not necessarily human-readable, but didn't put enough thoughts on that; there is also a known minor issue with generated deserialization implementations (#42). People seems to have confused on this behavior though, so I'm not sure how to change that without incurring a big performance hit.

**Comment by iamsebastian** [comment]
Hooray.

Thanks for your quick answer, @lifthrasiir . I could not find that answer on the whole web.

For the moment, I will parse the models by myself and will not use `RustcDecodable` macro, but the `Impl Display` to send a date representation via JSON, which can flawlessly be interpreted by the JavaScript engines.

```rust
impl ToJson for User {
    fn to_json(&self) -> Json {
        let mut map = BTreeMap::new();
        map.insert("email".to_string(), self.email.to_json());
        map.insert("real_name".to_string(), self.real_name.to_json());
        map.insert("id".to_string(), self.id.to_json());
        map.insert("attributes".to_string(), self.attributes.to_json());
        map.insert("created_at".to_string(), Json::String(format!("{}", self.created_at)));
        map.insert("updated_at".to_string(), Json::String(format!("{}", self.updated_at)));
        map.insert("deleted_at".to_string(), Json::String(format!("{}", self.deleted_at)));
        map.insert("is_deleted".to_string(), Json::String(format!("{}", self.deleted_at >= self.created_at)));
        map.insert("bank_id".to_string(), self.bank_id.to_json());
        Json::Object(map)
    }
}
```

... will response with:

```json
{
   "email" : "hero@frontbar",
   "bank_id" : 9,
   "id" : 37,
   "updated_at" : "1970-01-01 00:00:00",
   "attributes" : "a_hero",
   "created_at" : "2016-07-27 06:27:09",
   "real_name" : "The Hero",
   "deleted_at" : "1970-01-01 00:00:00",
   "is_deleted" : "false"
},
```

---

## Meta

By the way: Your *formular* (for the timestamp) does not seems to be correct. I gave it a try to correct it, but it is also not right:

```sh
> ymdf = 16518419;
16518419
> (ymdf >> 13) - 1
2015
> (ymdf >> 13)
2016
> ((ymdf >> 4) & 511) -1
208
> (ymdf >> 13) * 86400 * 365 + (((ymdf >> 4) & 511) -1) * 86400
63594547200
> new Date((ymdf >> 13) * 86400 * 365 + (((ymdf >> 4) & 511) -1) * 86400)
Fri Jan 07 1972 02:09:07 GMT+0100 (CET)
> y = (ymdf >> 13)
2016
> doy = ((ymdf >> 4) & 511) -1
208
> stamp = 86400 * ((y * 365 + y / 4 - y / 100 + y / 400) - (1969 * 365 + 1969 / 4 - 1969 / 100 + 1969 / 400) + doy)
1501147943.9999967
> new Date(stamp)
Sun Jan 18 1970 09:59:07 GMT+0100 (CET)
> new Date().getTime()
1469772404745
> stamp = 86400 * ((y * 365 + y / 4 - y / 100 + y / 400) - (1969 * 365 + 1969 / 4 - 1969 / 100 + 1969 / 400) + doy) * 1000
1501147943999.9966
> new Date(stamp)
Thu Jul 27 2017 11:32:23 GMT+0200 (CEST)
> stamp = 86400 * ((y * 365 + y / 4 - y / 100 + y / 400) - (1970 * 365 + 1970 / 4 - 1970 / 100 + 1970 / 400) + doy) * 1000
1469590991999.9924
> new Date(stamp)
Wed Jul 27 2016 05:43:11 GMT+0200 (CEST)
> new Date(((ymdf >> 13) - 1970) * 86400 * 365.2382248 * 1000)
Fri Jan 01 2016 00:00:00 GMT+0100 (CET)
```

As you see, one of the last lines:

```sh
> stamp = 86400 * ((y * 365 + y / 4 - y / 100 + y / 400) - (1970 * 365 + 1970 / 4 - 1970 / 100 + 1970 / 400) + doy) * 1000
1469590991999.9924
> new Date(stamp)
Wed Jul 27 2016 05:43:11 GMT+0200 (CEST)
```
Differs from the original one *(2016-07-27 06:07:08)* with ~ 24 minutes.

**Comment by lifthrasiir** [comment]
Ah, I've expected the division operator (`/`) to be a floor division (yes, it should be a floor division, otherwise negative years won't work). As you seem to use JavaScript, the following should work:

```js
> ymdf = 16518419;
16518419
> y = (ymdf >> 13) - 1;
2015
> doy = ((ymdf >> 4) & 511) -1;
208
> ndaysuptoyear = y => y * 365 + (y / 4 | 0) - (y / 100 | 0) + (y / 400 | 0);
[Function]
> new Date((86400 * (ndaysuptoyear(y) - ndaysuptoyear(1969) + doy)) * 1000)
Wed Jul 27 2016 09:00:00 GMT+0900 (KST)
```

The resulting `Date` is the midnight UTC---you also need to add `secs * 1000` for the full result. If you want to get the subsecond result, you should be aware that `frac` may exceed 10<sup>9</sup> for a leap second (and the UNIX timestamp can never express a leap second correctly).

**Comment by iamsebastian** [comment]
As this answered my initial question, I will close this issue.

Thanks again for the clarification, @lifthrasiir.
