### ISSUE TITLE
chrono::Local::now returns the next day

### ISSUE THREAD

**Issue by lukebitts** [lifthrasiir/rust-chrono#85]
The following code:

	extern crate chrono;

	fn main() {
	    println!("{:?}", chrono::Local::now());
	}

returns `2016-08-02T18:48:29.873191700-03:00` in my machine and a all others where my software is running. The dates returned were correct for the entire month of July, but the first day of August is being skipped. When I ran the code the datetime in my system was 2016-08-01, 18:48:29 and the timezone is GMT-3. If I change the date to 31 of July, the date returned is correct, other dates in August also return the next day.

Am I misunderstanding something about the way the library works, or is this a bug?

**Comment by lifthrasiir** [comment]
That is strange, but I was unable to replicate the result (mainly via manipulating the `TZ` environment variable). Is your copy of Chrono the latest version (0.2.22)? If so, what operating system and libc (if you happen to use non-system libc) do you use? Can you replicate it anytime by setting `TZ`?

**Comment by lukebitts** [comment]
I'm using the latest version, yes. The OS on my machine is Windows 10 and the production machines are running Windows 7. There is no TZ env variable set on my system. Changing the timezone in the Date/Time Settings still gave me the wrong result. Is there a specific timezone I should try?

I don't know if this is relevant, but I tested September and the dates are correct, August always returns the next day.

**Comment by lifthrasiir** [comment]
@lukebitts Hmm, I can ask you to check the following:

- Does the positive offsets (FYI, I'm on UTC+9) work correctly?
- There are two flavors of Rust in Windows, namely `msvc` and `mingw`; which one did you install?

I'll get the Windows machine within hours, so that I can retry the experiment there.

**Comment by lukebitts** [comment]
* Changing the timezone to GMT+9 returns `2016-08-03T22:45:06.028672700+09:00`. The date time of my machine was still 2nd of August.
* I'm using rustup, I think it installs mingw by default. `rustc --version` returns `rustc 1.11.0-nightly (bb4a79b08 2016-06-15)`. Is this enough? 

I ran some tests here to see if I could figure out where the bug was coming from. As you probably know `chrono::Local::now()` is a call to `tm_to_datetime(stdtime::now())`. `stdtime` is an alias to the `time` crate. 
The date part of the `chrono::DateTime<Local>` is built using `time::Tm::tm_yday`. I tried running `time::now()` directly and apparently it skips the day 213 of the year for some reason? If my system's date is set to July 31, `tm_yday` is 212. If the date is set to August 1st, `tm_yday` is 214. So maybe this is a bug with the time crate and not the chrono crate?

**Comment by lifthrasiir** [comment]
@lukebitts Huh, you are right, and the situation is very interesting! It is not a bug of Chrono but libtime... and I am very nervous of that now.

In my Windows machine the `datetime::tests::test_datetime_with_timezone` test fails even with my local time zone. (It gets `Local::now()`, converts to `UTC` and back to `Local` to check if they are identical; in this particular case the former is skewed by one day and the latter is by two days.) Ultimately I arrived at [this code](https://github.com/rust-lang-deprecated/time/blob/4c81709/src/sys.rs#L398-L407), which reads...

```rust
        fn yday(year: i32, month: i32, day: i32) -> i32 {
            let leap = if month > 2 {
                if year % 4 == 0 { 1 } else { 2 }
            } else {
                0
            };
            let july = if month > 7 { 1 } else { 0 };

            (month - 1) * 30 + month / 2 + (day - 1) - leap + july
         }
```

...which is very wrong. Besides from an obvious problem of Julian calendar it is completely wrong for August and later. I'll file a bug to the upstream. Thank you!
